.Dd 6/21/10             
.Dt switchbrowser 1     
.Os Darwin
.Sh NAME                
.Nm switchbrowser
.Sh SYNOPSIS            
.Nm
.Op Bundle Identifier or Shorthand
.Sh DESCRIPTION         
With an argument,
.Nm
directs OS X to open webpages over the HTTP and HTTPS protocols by default with the application of the given bundle identifier. 
Without an argument,
.Nm
lists the bundle identifiers of available applications which can bet set as HTTP/HTTPS handlers.
.Pp
Options:
.Bl -tag -width -indent
.It [Bundle Identifier or Shorthand] (Optional)
The bundle identifier of the app to be set as the default, e.g. com.apple.safari. A number of shorthands are also available: safari, firefox, opera, webkit, chrome, camino, flock.
.El